#!/bin/sh

set -e

lb config noauto \
        --clean \
        --ignore-system-defaults \
        --mode debian \
        --debian-installer live \
        --distribution trixie \
        --zsync false \
        --update true \
        --color \
        --binary-image iso-hybrid \
        --apt apt \
        --apt-source-archive false \
        --backports false \
        --architecture amd64 \
        --archive-areas "main non-free non-free-firmware contrib" \
        --image-name blue-live \
        --iso-publisher piratax007 \
        --linux-packages "linux-image linux-headers" \
        --source true \
        --bootappend-live "boot=live components locales=en_US.UTF-8 keyboard-variants=altgr-intl persistence persistence-encryption=luks" \
"${@}"
